version: '3.9'
services:
  keycloak-postgres:
    image: 'postgres:16.2-bullseye'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "keycloak", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=keycloak'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
    networks:
      - local
    ports:
      - '5433:5432'
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command:
      - start-dev
    depends_on:
      - keycloak-postgres
    environment:
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=password'
      - 'KC_DB=postgres'
      - 'KC_DB_USERNAME=postgres'
      - 'KC_DB_PASSWORD=password'
      - 'KC_DB_URL=jdbc:postgresql://keycloak-postgres/keycloak'
      - 'KC_HEALTH_ENABLED=true'
      - 'KC_HTTP_ENABLED=true'
      - 'KC_METRICS_ENABLED=true'
      - 'KC_HOSTNAME_URL=http://localhost:8090'
      - 'KC_PROXY=reencrypt'
    networks:
      - local
    ports:
      - '8090:8080'
      - '8787'

networks:
  local:
    name: local
    driver: bridge